### ISSUE TITLE
Building assets with gulp fails -> improve installation

### ISSUE THREAD

**Issue by thinkh** [jcc/vue-laravel-example#2]
I ran `npm install`. The command `gulp` results in the following message:

```
$ gulp
bash: gulp: command not found
```

Then I installed gulp globally `npm install -g gulp`. Running the command `gulp` again results in the following error:

```
$ gulp
module.js:472
    throw err;
    ^

Error: Cannot find module 'laravel-elixir-vue'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Git\vue-laravel-example\gulpfile.js:3:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

It seems that the dependency `npm install laravel-elixir-vue` is missing. After installation and running `gulp` again, the build process works.

**Comment by jcc** [comment]
You try to delete the directory of the `node_modules` and run the shell `npm install` again. You also can use the `yarn` instead of the `npm`.
