### ISSUE TITLE
gulp找不到模块

### ISSUE THREAD

**Issue by jkgeekJack** [jcc/vue-laravel-example#4]
已执行npm install,composer install,根目录下的node_modeule已有laravel-elixir和laravel-elixir-vue-2模块
报如下的错,请问是环境变量问题还是路径问题
```
module.js:328
    throw err;
    ^

Error: Cannot find module 'laravel-elixir-vue2'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/xjk/php/vue-laravel-example/gulpfile.js:3:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

```

**Comment by jcc** [comment]
你好，这是 `npm install` 的时候出现问题，导致会报这个错误，你可以尝试删除 `node_modules` 后重新 `npm install`，当然你也可以用 `yarn` 替代 `npm` 。 #2

**Comment by jcc** [comment]
#2

**Comment by rshuzz** [comment]
我把node_module删除也还会报错，怎么回事？   
 throw err;
    ^

Error: Cannot find module 'laravel-elixir-vue'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\wamp\www\vl\gulpfile.js:3:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by jcc** [comment]
@rshuzz 请尝试翻墙重新安装。或者使用 `yarn` 替代 `npm`
